language: objective-c  
osx_image: xcode8.3
script: xcodebuild clean test -project MMPixelSdk.xcodeproj -scheme MMPixelSdk -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' CODE_SIGNING_REQUIRED=NO